### ISSUE TITLE
Cant configure project

### ISSUE THREAD

**Issue by create3000** [tdz/gtkglext#3]
I tried to build gtkglext, when running: 

git clone git://github.com/tdz/gtkglext.git
cd gtkglext/cd gtkglext/
./bootstrap
./configure 

the following error occured:

./configure: line 16192: syntax error near unexpected token `1.30.0'
./configure: line 16192:`GOBJECT_INTROSPECTION_CHECK(1.30.0)'

Good luck and good night
Holger Seelig

**Comment by diegotoral** [comment]
try install girepository (libgirepository on Ubuntu).

**Comment by create3000** [comment]
Yes it compiles now, but it is hard for me to integrate it into my project. I am working on Titania a X3D viewer (https://launchpad.net/titania) an I am full of hope that gtkglext will accelerate the gl performance. When is it expected to land in the Ubuntu repos?

**Comment by tanty** [comment]
Maybe gtkglext dependencies should be more clearly stated but this looks like an invalid issue.
